# Numpy
## Methods

#### 1. Numpy Array

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### 2. Numpy Arange

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,12,3) #(a,b,c) a :awal b :akhir c:step (arange propertiesnya mirip seperti range.)

array([0, 3, 6, 9])

In [8]:
arr = np.arange(1,11)

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[7] #array propertiesnya mirip list, bisa di indexing.

8

In [11]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[[1,3,5,7]] # indexing untuk mengambil value dari index (arr[[idx]])

array([2, 4, 6, 8])

In [13]:
arr[[1,3,5,7]] = 100 #replacing value dari array dari index 

In [14]:
arr[[1,3,5,7]]

array([100, 100, 100, 100])

In [15]:
arr #melihat index dan value dari array

array([  1, 100,   3, 100,   5, 100,   7, 100,   9,  10])

In [16]:
slice_of_arr = arr[1:5]
slice_of_arr

array([100,   3, 100,   5])

In [17]:
slice_of_arr[:] = 0 #mengganti value dari array

In [18]:
slice_of_arr

array([0, 0, 0, 0])

In [19]:
arr

array([  1,   0,   0,   0,   0, 100,   7, 100,   9,  10])

#### 3. Numpy Linspace

In [20]:
np.linspace(0,5,11) # (a,b,c) a:awal b:akhir c:step

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [21]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

#### 4. Numpy random.rand

In [22]:
np.random.rand(2) #array random sebanyak x kali dari range(0-1) yang probabilitas valuenya sama 

array([0.38879673, 0.26479699])

In [24]:
np.random.rand(5,4) #(a,b) a: row, b: col

array([[9.14537910e-01, 2.09937703e-01, 4.53032106e-01, 5.51891539e-01],
       [5.83594626e-01, 8.57886702e-01, 1.54407816e-01, 1.57543509e-01],
       [7.41066088e-01, 9.89136027e-01, 3.98492051e-01, 9.38022931e-02],
       [7.40054696e-01, 6.45981599e-01, 8.41749765e-01, 9.17086615e-01],
       [3.83912600e-04, 3.44294175e-01, 2.26255253e-01, 3.32882834e-01]])

#### 5. Numpy random.randn

In [25]:
np.random.randn(2)

array([-0.62850989, -0.33457985])

In [26]:
np.random.randn(5,4)

array([[ 1.23647309, -1.03719343, -1.60284082,  0.42727681],
       [ 0.14173449,  0.35755837,  1.64558596, -1.71032416],
       [-0.80371344, -1.05502229, -1.174409  , -1.71867387],
       [-1.36001361, -0.17962918, -0.22827724,  1.21778036],
       [-1.12361143,  0.17944028,  0.58041048,  1.86360605]])

#### 6. Numpy random.randint

In [27]:
np.random.randint(1,100,10)

array([48, 76, 25, 79, 29, 29, 96, 85, 35, 87])

# Array

### Atributes & Methods

#### 1. Array2D

In [33]:
array_2D = np.array([[5,10,15], [20,25,30], [35,40,45], [50,55,60]]) 
array_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [34]:
array_2D[1]

array([20, 25, 30])

In [35]:
array_2D[1][0]

20

In [38]:
array_2D[:2,1:] #axis 0 adalah row dan axis 1 adalah column, berlakunya hanya untuk arrays 2 dimensi

array([[10, 15],
       [25, 30]])

In [37]:
array_2D.shape

(4, 3)

#### 2. Array Reshape

In [39]:
array_2D.reshape(3,4) #merubah shapenya (a,b) a:row b:col

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [44]:
array_2D.reshape(-1,1)

array([[ 5],
       [10],
       [15],
       [20],
       [25],
       [30],
       [35],
       [40],
       [45],
       [50],
       [55],
       [60]])

#### 3. Array Numerical Method

##### max, min, argmax, argmin

In [53]:
arr

array([  1,   0,   0,   0,   0, 100,   7, 100,   9,  10])

In [54]:
arr.max()

100

In [55]:
arr.min()

0

In [56]:
arr.argmax()

5

In [57]:
arr.argmin()

1

#### 4. Array dtype

In [58]:
arr.dtype

dtype('int32')

In [59]:
arr1 = np.array(['1', 'test', '5.0'])

In [60]:
arr1.dtype

dtype('<U4')